spring:
  application:
    name: Order-Service
server:
  port: 8084
  datasource:
    url: jdbc:postgresql://localhost:5342/orderdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Enable H2 console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

#spring.datasource.url=jdbc:h2:mem:orderdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.show-sql=true

eureka:
  client:
  enabled: false
